spring:
  application:
    name: exam-system
  datasource:
    password: muzichuan26
    username: root
    url: jdbc:mysql://localhost:3306/exam_system
server:
  port: 7000
logging:
  level:
    web: trace
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.com.xuroot.entity